package com.ayantsoft.payroll.dto;
// Generated 19 Dec, 2016 6:58:25 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import com.ayantsoft.payroll.util.DateJsonDeserializer;
import com.ayantsoft.payroll.util.DateJsonSerializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * TaxPayerGroupMst generated by hbm2java
 */

public class TaxPayerGroupMstDto implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 4243317530458591540L;
	
	private Integer id;
	private Integer uperLimitAge;
	private Integer lowerLimitAge;
	private String groupName;
	private Date createdDate;
	private Boolean isActive;
	
	
	/*GETTER SETTER*/
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getUperLimitAge() {
		return uperLimitAge;
	}
	public void setUperLimitAge(Integer uperLimitAge) {
		this.uperLimitAge = uperLimitAge;
	}
	public Integer getLowerLimitAge() {
		return lowerLimitAge;
	}
	public void setLowerLimitAge(Integer lowerLimitAge) {
		this.lowerLimitAge = lowerLimitAge;
	}
	public String getGroupName() {
		return groupName;
	}
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}
	
	@JsonSerialize(using = DateJsonSerializer.class)
	public Date getCreatedDate() {
		return createdDate;
	}
	
	@JsonDeserialize(using = DateJsonDeserializer.class)
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Boolean getIsActive() {
		return isActive;
	}
	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
}
